### ISSUE TITLE
tsconfig.json missing

### ISSUE THREAD

**Issue by vdende** [NativeScript/sample-TelerikNEXT#17]
Hi,

When I import the project in Atom, it says it is missing tsconfig.json. Therefore the TS-files won't compile because of missing references, i.e.:

`main-page.ts(25,59): error TS2304: Cannot find name 'UIColor'.`

In Atom I can create an initial tsconfig.json, but there it is missing all the references of NativeScript.
Is there a way in which I can easy create the tsconfig.json for this project?

**Comment by tzraikov** [comment]
tsconfig.json is now included
